### ISSUE TITLE
Question: defining package dependencies

### ISSUE THREAD

**Issue by cmackenz** [Fried-Chicken/expo-monorepo#4]
How are you adding dependencies to your project? I see that react/expo (and some other things) are defined in root package.json file and in your RNA package.json.

Just wondering what your workflow is like for managing these dependencies.

Also, thanks for sharing this -- I was having quite a time trying to set this up myself.

**Comment by cmackenz** [comment]
Another sample here: https://github.com/spearson23/expo-yarn-workspaces/blob/master/packages/expo/package.json

Uses the `no-hoist` option

**Comment by Fried-Chicken** [comment]
Hey @cmackenz 

Glad you like it. I deliberately chose not to use the `nohoist` option. This is because it's much faster to install when you hoist the dependencies especially as your project grows in size. In terms of dependency management, I would say it really depends on a couple of factors.

Firstly, if you will be publishing your packages to `npm` or `private npm` instances. Then you need to update the expo dependencies in both the root `package.json` and the `package.json` in your application. You could also list them as peer dependencies in the package.json of your rna app and let the root package take responsibility of installing them.

Secondly, do you have third party consumers of your packages? If you do then again you need to handle updating the package.json in both places. Otherwise people installing will be missing dependencies.

However if you do not fall in to the first and second criterion then you can either set the versions in your root `package.json` as [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/#toc-how-to-use-it) or you can just update the root `package.json` and ignore the version `package.json` as when you run yarn all the packages are symlinked anyway.

I hope this answers your question.

**Comment by Fried-Chicken** [comment]
@cmackenz Can I close this question?

**Comment by cmackenz** [comment]
Thanks for the detailed response @Fried-Chicken!

Closing :)
